import combinatorics_topology_relation_holomorphic_dynamical_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace combinatorics_topology_relation_holomorphic_dynamical_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end combinatorics_topology_relation_holomorphic_dynamical_theorem_canonical_lane_mathlib
end HautevilleHouse
